name: New Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build the distribution
    runs-on: ubuntu-latest

    environment: release

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine wheel

      - name: Build binary wheel and a source tarball
        run: |
          python setup.py sdist bdist_wheel

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  github_release:
    name: GitHub Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.txt"

  publish_to_testpypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: release
      url: https://test.pypi.org/p/qlayers
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - name: Download the distribution packages
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/

  publish_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: release
      url: https://pypi.org/p/qlayers
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - name: Download the distribution packages
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
